

services:
  todos-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "todos-db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"

  todos-app:
    build: .
    restart: always
    ports:
      - "5206:5206"
      - "7007:7007"
    environment:
      - ASPNETCORE_URLS=http://+:5206
    depends_on:
      - todos-db