

services:
  todos-app:
    container_name: todos-app
    build: .
    restart: always
    ports:
      - "5206:5206"
      - "7007:7007"
    environment:
      - ASPNETCORE_URLS=http://+:5206
      - DB_HOST=todos-db
    depends_on:
      todos-db:
        condition: service_healthy

  todos-db:
    container_name: todos-db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /pgdata:/var/lib/postgresql/data/todos-db-data
    environment:
      POSTGRES_DB: "todos-db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: /var/lib/postgresql/data/todos-db-data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5