

services:
  todos-app:
    container_name: todos-app
    image: __TODOS_APP_IMAGE_NAME__
    restart: always
    ports:
      - "5206:5206"
      - "7007:7007"
    environment:
      - ASPNETCORE_URLS=http://+:5206
      - DB_HOST=todos-db
    depends_on:
      todos-db:
        condition: service_healthy
      todos-keycloak:
        condition: service_started

  todos-db:
    container_name: todos-db
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data/todos-db-data
    environment:
      POSTGRES_DB: "todos-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /var/lib/postgresql/data/todos-db-data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  todos-keycloak:
    container_name: todos-keycloak
    image: quay.io/keycloak/keycloak:26.0.5
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-data:/opt/keycloak/data
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"

      KC_DB: "postgres"
      KC_DB_URL_HOST: "todos-db"
      KC_DB_URL_DATABASE: "todos-db"
      KC_DB_USERNAME: "postgres"
      KC_DB_PASSWORD: "postgres"
    depends_on:
      - todos-db
    command: "start-dev"

  todos-nginx:
    image: nginx:latest
    container_name: todos-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /s/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - todos-keycloak