

services:
  todos-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "todos-db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"

