replicaCount: 1

image:
  repository: ghcr.io/chernykh-dev/your-flow-backend-todos
  tag: master
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: api.master.your-flow.online
      paths:
        - /

namespace: master

database:
  name: todos-db
