name: Deploy on Master

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: ${{ secrets.GHCR_IMAGE_NAME }}:${{ github.head_ref || github.ref_name }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Clear old directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            rm -rf /home/${{ secrets.VPS_USER }}/todos

      - name: Copy files to VPS via SSH
        uses: appleboy/scp-action@master
        with:
          use_insecure_cipher: true
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/home/${{ secrets.VPS_USER }}/todos/"

      - name: Replace image name & restart container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/todos/TodoService
            
            sed "s|__TODOS_APP_IMAGE_NAME__|${{ env.IMAGE_NAME }}|" docker-compose.template.yml > docker-compose.yml
            
            docker pull ${{ env.IMAGE_NAME }}
            docker-compose down
            docker-compose up -d --build
